config/routes.rb
Rails.application.routes.draw do
  get 'bookings/invalidate'
  resources :bookings

  get 'rooms/myrooms'
  get 'rooms/unauthorized'
  resources :rooms
  resources :images
  devise_for :users
  scope "/admin" do
     resources :users
    end
  resources :roles
  resources :amenities
  resources :cities

   root 'cities#index'

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base
validates_presence_of :name, :description
validates_uniqueness_of :name

belongs_to :room
has_many :amenity_rooms
has_many :rooms, through: :amenity_rooms
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  # this method is responsible for invoking ability.rb 
  before_action :authenticate_user!, except: [:index, :show] 
  load_and_authorize_resource
  before_action :set_amenity, only: [:show, :edit, :update, :destroy]

  # GET /amenities
  # GET /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1
  # GET /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
  end

  # GET /amenities/1/edit
  def edit
  end

  # POST /amenities
  # POST /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to @amenity, notice: 'Amenity was successfully created.' }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1
  # PATCH/PUT /amenities/1.json
  def update
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to @amenity, notice: 'Amenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1
  # DELETE /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: 'Amenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amenity_params
      params.require(:amenity).permit(:name, :description, amenity_ids: [])
    end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/views/amenities/_form.html.erb
<%= form_for(@amenity) do |f| %>
  <% if @amenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

      <ul>
      <% @amenity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amenities/edit.html.erb
<h1>Editing Amenity</h1>

<%= render 'form' %>

<%= link_to 'Show', @amenity %> |
<%= link_to 'Back', amenities_path %>

app/views/amenities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Amenities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.name %></td>
        <td><%= amenity.description %></td>
        <td><%= link_to 'Show', amenity %></td>
        <% if can? :update, amenity %>
        <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <% end %>
        <% if can? :destroy, amenity %>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Amenity.new %>
<%= link_to 'New Amenity', new_amenity_path %>
<% end %>

app/views/amenities/new.html.erb
<h1>New Amenity</h1>

<%= render 'form' %>

<%= link_to 'Back', amenities_path %>

app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amenity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @amenity.description %>
</p>

<%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<%= link_to 'Back', amenities_path %>