config/routes.rb
Rails.application.routes.draw do
  get 'bookings/invalidate'
  resources :bookings

  get 'rooms/myrooms'
  get 'rooms/unauthorized'
  resources :rooms
  resources :images
  devise_for :users
  scope "/admin" do
     resources :users
    end
  resources :roles
  resources :amenities
  resources :cities

   root 'cities#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
	#mount_uploader :image, ImageUploader



	belongs_to :city
	belongs_to :user
	has_many :amenities
	has_many :images
	has_many :amenity_rooms
	has_many :amenities, through: :amenity_rooms

	accepts_nested_attributes_for :images

	after_create :send_email
	after_create :guest_to_host
	after_update :room_authorization_confirmation


	def guest_to_host 
		# use find_by bcz what if our first user is guest we dont knw the id
		role = Role.find_by_name("guest")
		host = Role.find_by_name("host")
		if (self.user.role_id == role.id)
			self.user.role_id = host.id
			self.user.save
		end
 	end

	def send_email
		Notification.isauthorized_confirmation(self).deliver!
	end

	def room_authorization_confirmation
		NotificationHost.authorized_confirmation(self).deliver!
	end
	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  load_and_authorize_resource
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @user = current_user
    @rooms = Room.all
    @images = Image.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @image = Image.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def myrooms
    @rooms = Room.all
  end
  def unauthorized
    @rooms = Room.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :price, :rules, :minimum_days, :address, :latitude, :longitude, :is_authorized, :city_id, :user_id, images_attributes:[:id, :image, :room_id])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :rules %><br>
    <%= f.text_field :rules %>
  </div>
  <div class="field">
    <%= f.label :minimum_days %><br>
    <%= f.text_field :minimum_days %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
    <p id = "addressError"></p>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
    <p id = "latitudeError"></p>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
    <p id = "longitudeError"></p>
  </div>

  <div class="field">
  <%= f.label :amenities %><br>
  <%= f.collection_check_boxes :amenity_ids, Amenity.all, :id, :name %>
  </div>

   <div class="field">
  <%= f.label :cities %><br>
  <%= f.collection_select :city_id, City.all, :id, :name, prompt: "select city" %>
  </div>
  <% if can? :update, @room %>
  <div class="field">
    <%= f.label :is_authorized %>
    <%= f.check_box :is_authorized %> 
  </div>
  <% end %>

  <div class="field">
    <%#= f.hidden_field :city_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= f.fields_for :images,@image do |ff| %>
    <%= ff.file_field :image %><br>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<script>
  var addressHandle = document.getElementById('room_address')
  var addressErrorHandle = document.getElementById('addressError')
  var latitudeHandle = document.getElementById('room_latitude')
  var longitudeHandle = document.getElementById('room_longitude')
  

addressHandle.onblur = function(){
    if(addressHandle.value == ""){
      addressErrorHandle.innerHTML = "Can't be blank";
    } else {
      addressErrorHandle.innerHTML = ""; 
      var addressSplit = addressHandle.value.split(" ");
      var addressJoin = addressSplit.join("+");
      console.log(addressJoin);
      var xhr = new XMLHttpRequest();
           xhr.open('GET',"https://maps.googleapis.com/maps/api/geocode/json?address="+addressJoin+"&key=AIzaSyBZEUR89PrVcJnWmRCySjIePLjjmGr_VlQ");
           xhr.onreadystatechange = function(){
            if(xhr.readyState == 4 && xhr.status == 200){
                var response = JSON.parse(xhr.responseText);
                      result = response.results;
                     var latitude = "";
                      var longitude = "";
                  result.forEach(function(res){
                     latitude = res.geometry.location.lat;
                     longitude = res.geometry.location.lng;
                    console.log(latitude);
                    console.log(longitude);
                  });
                  latitudeHandle.value = latitude;
                  longitudeHandle.value = longitude;
              }   
            };      
           xhr.send();
    }
  };

</script>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authorized Rooms</h1>
<h4><%= link_to 'My Room', rooms_myrooms_path %></h4>
<% if @user.present? %>
  <% if @user.role_id == Role.find_by_name("admin").id %>
    <h4><%= link_to 'Unauthorized Rooms', rooms_unauthorized_path %></h4>
  <% end %>
<% end %>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rules</th>
      <th>Minimum days</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Is authorized</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <% if room.is_authorized == true %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.rules %></td>
        <td><%= room.minimum_days %></td>
        <td><%= room.address %></td>
        <td><%= room.latitude %></td>
        <td><%= room.longitude %></td>
        <td><%= room.is_authorized %></td>
        <td><%= link_to 'Show', room %></td>
        <% if can? :update, room %>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <% end %>
        <% if can? :destroy, room %>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
 

</table>

<br>
<% if can? :create, Room.new %>
<%= link_to 'New Room', new_room_path %>
<% end %>

app/views/rooms/myrooms.html.erb
<h2>My Rooms <%#= @rooms.length %></h2>

<table>
 <thead>
   <tr>
     <th>Name</th>
     <th>Description</th>
     <th>Price</th>
     <th>Rules</th>
     <th>Minimum days</th>
     <th>Address</th>
     <th>Lat</th>
     <th>Lng</th>
     <th>Is authorized</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @rooms.each do |room| %>
   <% if room.user_id == current_user.id %>
     <tr>
       <td><%= room.name %></td>
       <td><%= room.description %></td>
       <td><%= room.price %></td>
       <td><%= room.rules %></td>
       <td><%= room.minimum_days %></td>
       <td><%= room.address %></td>
       <td><%= room.latitude %></td>
       <td><%= room.longitude %></td>
       <td><%= room.is_authorized %></td>
       <td><%= link_to 'Show', room %></td>
       <% if can? :update, room %>
       <td><%= link_to 'Edit', edit_room_path(room) %></td> 
       <% end %>
       <% if can? :destroy, room %>
       <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <% end %>
       <% end %>
     </tr>
   <% end %>
 </tbody>
</table>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Rules:</strong>
  <%= @room.rules %>
</p>

<p>
  <strong>Minimum days:</strong>
  <%= @room.minimum_days %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @room.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @room.longitude %>
</p>

<p>
  <strong>Is authorized:</strong>
  <%= @room.is_authorized %>
</p>
<p>
<strong>Image:</strong>
<% @room.images.each do |img| %>
  <%= image_tag img.image %>
<% end %>
</p>

<iframe
  width="1250"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCmI289vCsUvj4__rkKvjfdclWMrtl_PN0
    &q=<%= @room.latitude%>,<%= @room.longitude %>" allowfullscreen>
</iframe>

<% if user_signed_in? %>
<h3>Booking</h3>

<%= form_for @booking do |f| %>

<% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%#= f.label :user_id %>
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%#= f.label :room_id %>
    <%= f.hidden_field :room_id, value: @room.id %>
  </div>
 <!-- <div class="field">
    <%#= f.label :is_confirmed %>
    <%#= f.check_box :is_confirmed %> 
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>



<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/unauthorized.html.erb
<h4>Unauthorized Rooms : <%= @rooms.length %></h4>

	
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rules</th>
      <th>Minimum days</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Is authorized</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <% if room.is_authorized == false %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.rules %></td>
        <td><%= room.minimum_days %></td>
        <td><%= room.address %></td>
        <td><%= room.latitude %></td>
        <td><%= room.longitude %></td>
        <td>
        <%= form_for(room) do |f| %>
         <%= f.check_box :is_authorized %>
         <%= f.submit "authorize room" %>
        <% end %>
        </td>
        <td><%= link_to 'Show', room %></td>
        <% if can? :update, room %>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <% end %>
        <% if can? :destroy, room %>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>